cs_CZ = {
    "nameToolTip": "Zpět na výběr jazyku.",
    "nameAction": "Akce",
    "nameSign": "Podepsat",
    "nameVeri": "Ověřit",
    "nameChose": "Vyberte",
    "nameFile": "Soubor",
    "nameFolder": "Složka",
    "nameKey": "Klíč",
    "nameGen": "Generovat",
    "nameIncK": "Obsáhnout key.pub?",
    "nameY": "Ano",
    "nameN": "Ne",
    "nameSaveArch": "Uložit podepsaný archiv",
    "nameLoadArch": "Otevřít podepsaný archiv",
    "nameWait": "Prosím čekejte.",
    "namePrivKeyFilter": "Soukromý klíč (key.priv)",
    "nameZip": ["Standartní (*.zip)", "7zip (*7z)", "rar (*.rar)","unix gzip (*.tar.gzip)", "unix bzip2 (*.tar.bz2)", "unix lzma (*tar.lzma)"],
    "nameSignFinal": "Hotovo, soubor/složka je pedepsaný/á",
    "nameSlctVerFile": "Vyberte soubor pro ověření",
    "nameSlctPubKey": "Veřejný klíč nenalezen",
    "nameSlctSign":"Podpisový soubor nenalezen",
    "namePubKey":"Veřejný klíč (key.pub)",
    "nameSignFile":"Podpisový soubor (*.sign)",
    "nameBack": "Zpět",
    "nameSelect": "Vybrat",
    "nameVerifed":"Ověření proběhlo úspěšně",
    "nameKeyExist": "Klíč již existuje",
    "nameOverwrite": "Přepsat",
    "nameSlcOF": "Nová cesta",
    "nameMatchNF":"Podpisy se neshodují",
    "nameFileNF":"Soubor pro ověření nenalezen",
    "namePubNF":"Klíč key.pub nenalezen",
    "nameSignNF":"Soubor .sign nenalezen",
}

eng_US = {
    "nameToolTip": "Back to language choose.",
    "nameAction": "Action",    
    "nameSign": "Sign",
    "nameVeri": "Verify",
    "nameChose": "Chose",
    "nameFile": "File",
    "nameFolder": "Folder",
    "nameKey": "Key",
    "nameGen": "Generate",
    "nameIncK": "Include key.pub?",
    "nameY": "Yes",
    "nameN": "No",
    "nameSaveArch": "Save Signed archive",
    "nameLoadArch": "Open Signed archive",
    "nameWait": "Please wait.",
    "namePrivKeyFilter": "Private key (key.priv)",
    "nameZip": ["Standart (*.zip)", "7zip (*7z)", "rar (*.rar)","unix gzip (*.tar.gzip)", "unix bzip2 (*.tar.bz2)", "unix lzma (*tar.lzma)"],
    "nameSignFinal": "Done, file/folder is signed",
    "nameSlctVerFile": "Select file to verify",
    "nameSlctPubKey": "Public key not found",
    "nameSlctSign":"Sign file not found",
    "namePubKey": "Public key (key.pub)",
    "nameSignFile": "Signed file (*.sign)",
    "nameBack": "Back",
    "nameSelect": "Select",
    "nameVerifed": "Verification was successful",
    "nameKeyExist": "Keys alredy exist",
    "nameOverwrite": "Overwrite",
    "nameSlcOF": "New path",
    "nameMatchNF":"Signatures do not match",
    "nameFileNF":"Authentication file not found",
    "namePubNF":"key.pub file not found",
    "nameSignNF":".sign file not found",
}
appLang = {
    "cs_CZ": cs_CZ,
    "eng_US": eng_US
}
